name: Deploy to Production

# トリガー：mainブランチにプッシュされた時に実行
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. SSHキーを設定します
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 2. 接続先のサーバーを、既知のホストとして登録します
      - name: Add remote host to known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 3. サーバーにSSH接続して、デプロイコマンドをまとめて実行します
      - name: Deploy to Production Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd /var/www/rebuild-project &&
            git pull origin main &&
            docker-compose up --build -d
          '
